### ISSUE TITLE
Failing to do repeated TCP connections with error "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by sirilvk** [majek/openonload#10]
While running my application (which does a lot of tcp connections one after another) over onload (openonload), it fails to connect/receive after receiving some data. Its fails saying "Resource temporarily unavailable". However my application works perfectly fine when not run on onload. I haven't done any configuration for onload (do I need to set anything for such a requirement?).

Am using the Solarflare SFN8522 plus card and its currently having settings;
galileo@local:~$ ethtool -i ens6f0np0
driver: sfc
version: 4.13.1.1034
firmware-version: 6.6.0.1017 rx1 tx1
expansion-rom-version:
bus-info: 0000:03:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: yes

Also my application uses the same interface for receiving huge number of multicast messages at the same time.

**Comment by majek** [comment]
Please consider upstreaming these comments to openonload authors. This git repo is just a clone of the tgz
