### ISSUE TITLE
char* comparing with char

### ISSUE THREAD

**Issue by gchebanov** [majek/openonload#2]
src/tests/ef_vi/efvi_sfw.c:327 if( remainder == '\0' ) /* No vlan */

**Comment by majek** [comment]
https://github.com/majek/openonload/blob/5e26bb8147134552e918f5f40dd0ddbf5064feb0/src/tests/ef_vi/efvi_sfw.c#L327

Fancy letting know the solarflare people about this?

**Comment by gchebanov** [comment]
Have not yet. If you can do this, I would be very grateful.
