### ISSUE TITLE
add scientific to redhat list

### ISSUE THREAD

**Issue by mojothemonkey** [majek/openonload#9]
could someone add 'scientific' to list of redhat dists in the spec file? (line 59)..

%define redhat %(lsb_release -is | grep -qi -e redhat -e cent -e fedora -e oracle && echo 1; lsb_release -is | grep -qi suse && echo 0)

**Comment by majek** [comment]
Please consider upstreaming these comments to openonload authors. This git repo is just a clone of the tgz.
